#
# compose the dokcer wordpress,phpMyAdminm and mariadb
#
wordpress_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: examplepass

wordpress:
  image: wordpress
  links:
    - wordpress_db:mysql
  ports:
    - 80:80

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - wordpress_db:mysql
  ports:
    - 8181:80
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
    PMA_USER: root
    PMA_PASSWORD: examplepass